# Generated by Django 6.0.5 on 2026-06-19 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_time', models.DateTimeField(auto_now=True)),
                ('monitor_mode', models.CharField(default='full', max_length=20)),
            ],
        ),
    ]
