# Generated by Django 6.0.5 on 2026-06-19 11:45

from django.db import migrations

def migrate_data(apps, schema_editor):
    Server = apps.get_model('core', 'Server')
    Monitor = apps.get_model('core', 'Monitor')
    
    servers = Server.objects.all().order_by('timestamp')
    if not servers.exists():
        return
        
    current_mode = None
    session_start = None
    session_end = None
    
    for server in servers:
        if current_mode is None:
            current_mode = server.service_mode
            session_start = server.timestamp
            session_end = server.timestamp
        elif server.service_mode == current_mode:
            session_end = server.timestamp
        else:
            Monitor.objects.create(
                timestamp=session_start,
                monitor_mode=current_mode
            )
            # update live_time separately since it's auto_now
            m = Monitor.objects.last()
            Monitor.objects.filter(id=m.id).update(live_time=session_end)
            
            current_mode = server.service_mode
            session_start = server.timestamp
            session_end = server.timestamp
            
    if current_mode is not None:
        Monitor.objects.create(
            timestamp=session_start,
            monitor_mode=current_mode
        )
        m = Monitor.objects.last()
        Monitor.objects.filter(id=m.id).update(live_time=session_end)
        
    # Cleanup Server duplicates
    prev_online = None
    prev_count = None
    to_delete = []
    
    for server in servers:
        if server.is_online == prev_online and server.player_count == prev_count:
            to_delete.append(server.id)
        else:
            prev_online = server.is_online
            prev_count = server.player_count
            
    if to_delete:
        Server.objects.filter(id__in=to_delete).delete()

def reverse_migrate(apps, schema_editor):
    Monitor = apps.get_model('core', 'Monitor')
    Monitor.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monitor'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate)
    ]
