# Generated by Django 6.0.5 on 2026-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='service_mode',
        ),
    ]
